"""Fixed comparison texts for Falcon dev vs prod (shared en-US / en-UK / en-IN)."""

from __future__ import annotations

ARENA_COMPARISON_TEXTS: tuple[str, ...] = (
    "I've checked your order for the KitchenAid mixer. It is now ready for pickup at our Stanford Shopping Centre store.",
    "NASA's Deep Space Network is a global system of antennas that communicates with interplanetary spacecraft, essential for space exploration.",
    "\"Ever make something happen when you were angry or scared?\" The boy hesitates, remembering shattered glass and startled snakes.",
    "\"I thought I might find you here,\" murmurs an elderly wizard, tucking a curious lighter-like device back into his robe.",
    "\"It's a sign,\" one whispers in a robe, dripping hair. \"It's a smoke alarm,\" comes the reply. \"Signs don't flash this loud.\"",
    "A 'jiffy' is an actual unit of time in physics, representing the time light takes to travel one centimeter in a vacuum.",
    "A brick wall becomes a doorway with a few well-placed taps; beyond it, a city of wands, owls, and cauldrons hums to life.",
    "A cockroach can live for weeks without its head because it breathes through small holes in its body segments.",
    "A day on Venus is longer than a year on Venus; it takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun.",
    "A light rain band will pass your route to work in twenty minutes. Bring an umbrella if you're heading out soon.",
    "A new episode of Emily in Paris came out on Netflix today. Should I download this one before your flight tonight?",
    "A photon takes 200,000 years to travel from the Sun's core to its surface, then just 8 minutes to reach Earth.",
    "A search warrant authorizes law enforcement officers to enter premises and seize evidence in connection with a suspected crime.",
    "A shrimp's heart is located in its head; specifically, it's in the thorax which is covered by the head shield.",
    "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "A tabby cat sits very still on a garden wall—then, with a soft ripple of shadow, becomes a stern professor in emerald robes.",
    "A teaspoon of neutron star material would weigh about 6 billion tons, equivalent to the weight of a mountain.",
    "A word cloud with business terms, largest to smallest: Business, Success, Idea, Money, Creative, Presentation, and other smaller business terms.",
    "A writ of habeas corpus is used to bring a prisoner or other detainee before the court to determine if the person's imprisonment or detention is lawful.",
    "Across the water you can see the Statue of Liberty, holding her torch high as she has welcomed millions to America.",
    "Air quality within a 2 mile radius has dropped to hazardous levels due to heavy pollution. Keep windows closed and limit outdoor exercise.",
    "An adult human is made up of approximately 7 octillion atoms, a number with 27 zeros.",
    "An octopus has three hearts, nine brains, and blue blood; they are among the most intelligent invertebrates.",
    "And he's driving forward now, past one, past two, looks up, strikes it… oh, the keeper's just managed to get a hand to it.",
    "And there's the whistle—settle in, because this one promises bite, bravery, and a little bit of brilliance.",
    "Antarctica's Dry Valleys haven't seen rain for nearly 2 million years and are one of the driest places on Earth.",
    "Approximately 90% of the cells in the human body are not human but are bacteria, fungi, and other microbes.",
    "At the next intersection, turn left onto George Street. After 400 meters, your destination will be on the left.",
    "Automatic renewal terms must be clearly disclosed under Australian consumer protection rules.",
    "Badges? We ain't got no badges! We don't need no badges!",
    "Bananas are slightly radioactive due to their potassium content, which includes the radioactive isotope potassium-40.",
    "Based on your eating this week, you're short on fiber intake. Lentils or chickpeas at dinner would help.",
    "Before accepting a settlement, understand that signing a release agreement may permanently waive your right to bring future claims.",
    "Before us is Tower Bridge in London, a symbol of Victorian engineering that still opens for ships on the Thames.",
    "Behind me is the Colosseum in Rome, nearly two thousand years old, yet still echoing with the roar of history.",
    "Behind us is the Golden Gate Bridge, stretching across the bay in its unmistakable orange-red.",
    "Ben steadies himself at his desk, eyes on the inbox count as if it were a heart monitor; across the floor, a birthday song swells around a cake he didn't order.",
    "Blue Origin's New Shepard rocket successfully completed suborbital flights, including carrying founder Jeff Bezos to space in 2021.",
    "Bond yields move inversely to prices, a concept that often confuses first-time investors but underpins fixed-income strategy.",
    "Butterflies can taste with their feet; they have taste receptors on them to help find food.",
    "Caffeine binds to adenosine receptors in the brain, preventing adenosine from sending its normal signal that it's time to slow down and rest.",
    "Chemotherapy is a type of treatment that uses medicine to kill cancer cells. Imunotherapy is therapy in which drugs are used to stimulate the body's immune system to treat cancer.",
    "China's Chang'e 4 mission achieved the first soft landing on the far side of the Moon in 2019, exploring previously uncharted lunar territory.",
    "Chronic stress raises cortisol levels, which over time can impair immune function and memory.",
    "Coming up next, a man who can solve a Rubik's Cube blindfolded — while juggling — and I've seen the rehearsal, it's absurd.",
    "Compounding is often called the eighth wonder of the world, yet most investors underestimate how time magnifies returns.",
    "Cooling-off periods give consumers the right to cancel certain contracts within a prescribed timeframe, often 14 days.",
    "Copper prices slipped below $8,000 a tonne, reflecting weaker construction demand across key Asian economies.",
    "Core workout suggestion: three planks, thirty seconds each, to finish strong today.",
    "CRISPR gene editing allows scientists to target and modify specific DNA sequences with remarkable precision.",
    "Currency traders are bracing for volatility as the ECB signals it may recalibrate its bond-buying programme sooner than expected.",
    "Day 1 million of trying to sound like the AI voice narrator guy. What do you guys think?",
    "Day 4 of going to the gym: my arms don't work anymore, but at least my water bottle collection is thriving",
    "Deep sleep is when your brain consolidates memories and your body releases growth hormone for tissue repair.",
    "Delegated legislation allows ministers or agencies to make rules under authority granted by an Act of Parliament.",
    "Depression is associated with changes in neurotransmitters like serotonin, dopamine, and norepinephrine.",
    "Despite a net loss of €42 million for the first half of 2025, the company forecasts significant earnings growth at 31.7% annually",
    "Diagram of Soil Layers on Earth, from top going down: organic layer, topsoil layer, subsoil layer, parent rock layer, and last bedrock layer.",
    "Diamonds rain on Saturn and Jupiter; lightning storms turn methane into soot, which hardens into falling diamonds.",
    "Diplomatic immunity protects accredited diplomats from being subject to the jurisdiction of local courts.",
    "Doing calming activities before bedtime, such as taking a bath or using relaxation techniques, might promote better sleep.",
    "Double jeopardy prevents a person from being tried twice for the same offence once acquitted or convicted.",
    "Each ETF has an investment mandate, and that outlines its objectives, approach, and any guidelines on what the ETF can or can't invest in.",
    "Entrapment occurs when law enforcement induces someone to commit a crime they would not have otherwise committed.",
    "ESA's Gaia spacecraft is creating a 3D map of over a billion stars in our galaxy, improving our understanding of the Milky Way's structure.",
    "Even small amounts of blue light from phones or tablets can suppress melatonin production and delay your natural sleep cycle.",
    "Extradition treaties enable countries to surrender individuals accused or convicted of crimes to another jurisdiction.",
    "Feeling lucky? I can shuffle your saved restaurants and pick tonight's dinner spot for you two.",
    "Flexibility work, like yoga or dynamic stretching, helps maintain joint mobility and reduces injury risk.",
    "Global dealmaking reached $2.6 trillion in the first seven months of the year, the highest since the 2021 pandemic-era peak.",
    "Gold held steady at $1,950 an ounce, as traders weighed softer US inflation data against a stronger dollar.",
    "Good evening wherever you're tuning in from, the lights are on, the scarves are out, and you can feel the buzz building in every corner of this ground.",
    "Good morning. Today in London it will be partly cloudy with a high of 17 degrees. You have three events on your calendar.",
    "Good morning. You have two priority messages from overnight, with no priority emails requiring attention.",
    "Gordon Ramsay would probably cry if he saw me call this burnt omelette rustic.",
    "Greatness does not roar into existence; it grows slowly, piece by piece, in the discipline of ordinary days.",
    "Green flags again, he times the restart beautifully, launches out of the final corner, and the field snakes behind him on cold tyres.",
    "He steps inside one, dances past another, looks up, hits it… and the keeper gets a strong wrist to it.",
    "Heart rate elevated beyond your usual range. Would you like me to log this for your doctor?",
    "Here we are standing on the bustling streets of Tokyo's Shibuya Crossing, where thousands pour through every signal change.",
    "Here's the break—pace to burn, options left and right, picks left, across the face… and somehow it stays out.",
    "Here's the three most effective exercises that will transform your physique. No need to do fancy machine exercises.",
    "High-intensity interval training can burn calories efficiently while improving cardiovascular and muscular endurance.",
    "Hope is not a gift you stumble upon; it is forged in your choices, carved by your persistence, and carried forward in faith.",
    "Hot water can freeze faster than cold water under certain conditions, a phenomenon known as the Mpemba effect.",
    "Humans share 50% of their DNA with bananas, highlighting the common genetic heritage of all living organisms.",
    "I can confirm your booking at the downtown hotel for 12 May. Would you like me to please add late check-in so your room is kept past 10 p.m.?",
    "I can confirm your credit card refund of $82.40 was processed on April 15th. Please allow three business days for it to appear.",
    "I can confirm your doctor's appointment for May 6th at 2 p.m. Would you like me to send a reminder the day before?",
    "I can confirm your flight AA7396 is booked for May 15th at 10:30 a.m. Would you like to me add your system listed meal preference to this flight?",
    "I can confirm your hotel reservation in Chicago for two nights. If you'd like an extra night, I can check availability and hold the room for you.",
    "I can confirm your return ticket was successfully changed to May 20th. Would you like me to email the updated itinerary?",
    "I can see you've reached gold tier this year. That gives you free shipping on every order. Would you like me to review the other benefits with you?",
    "I can see your flight to Singapore on June 2nd is confirmed in economy. Would you like me to check seat upgrades in business class?",
    "I can see your mobile plan is eligible for a free upgrade to 100 gigabytes of data per month. Would you like me to activate it?",
    "I can see your Netflix subscription is set to renew on April 25th. Would you like me to update your payment method so there's no interruption?",
    "I can see your order 7A41 for a MacBook shipped yesterday from Mascot warehouse and is due Friday. Could you please confirm if this is the product?",
    "I can see your Spotify Premium is billed via Apple. You'll need to check your Apple PayID details — would you like me to guide you through that process?",
    "I can see your taxi booking is confirmed for pickup at 6:30 a.m. outside your hotel lobby.",
    "I can see your train booking from Melbourne to Sydney on April 18th has been issued. Would you like me to email the e-ticket to you now?",
    "I can see your travel insurance includes coverage for lost luggage. Would you like me to open a claim for your missing bag?",
    "I can't help how I speak. I'm just trying to do the best that I can. Let me know in the comments what you think.",
    "I found 4 options that are healthy and match your typical preferences. I'd recommend going with the salmon sashimi bowl from Bowl House.",
    "I found three cinema showtimes for the new Dune movie tomorrow near you. At Ritz Cinema, there are showings at 12pm, 3:30pm, 6pm.",
    "I love the calls where the fix is instant and you can hear the relief spread like sunshine through the phone.",
    "I noticed \"descaling the espresso machine\" on your to-do list. I can guide you through it whenever you're ready.",
    "I noticed you logged your morning tablets, but not your evening dose yet. When you're ready, please take them or update the log.",
    "I see you still have \"follow-up on new article proposal\" pending on today's to-do list. Please let me know if you'd like me to draft a message.",
    "I see your Samsung Galaxy S24 was delivered on April 10th. Please let me know if you'd like me to activate the warranty registration on your behalf.",
    "I think the data makes it pretty clear that exercise has a bigger impact on length and quality of life than any of the other metrics.",
    "I thought growing up meant getting answers, but it turns out it just means learning to live with better-phrased questions.",
    "I used to chase certainty like it was oxygen, but now I think the not-knowing is where all the living actually happens.",
    "I wanted to be extraordinary, but sometimes I think surviving the ordinary is the braver kind of work.",
    "I wonder if forgiveness is really about the other person, or if it's just a way of setting myself free without asking permission.",
    "I'm so sorry your parcel is late. Let me please check the status for you now. Do you have a FedEx tracking ID I could use?",
    "I'm sorry your printer is showing error code 31. A reset usually resolves this — would you like me to guide you through the steps?",
    "I've checked your auto insurance policy. It covers windshield replacement with no excess. Would you like me to schedule a repair?",
    "I've checked your gym membership and it's currently frozen until June 16. I can see you do still have one more freeze available this year.",
    "I've checked your health insurance. You're covered for dental cleanings twice per year. Would you like me to book one now?",
    "I've checked your insurance policy, and your roadside assistance is active. Would you like me to dispatch a tow truck to your location now?",
    "I've checked your internet usage. You've used 85% of your monthly allowance. Would you like me to top up your plan?",
    "I've checked your loyalty account. You now have 1,200 points available. Would you like me to redeem them for a $10 voucher?",
    "I've confirmed your Uber booking for 8 p.m. tonight. The driver will arrive in a black Toyota Camry.",
    "I've dimmed the lights to fifty percent brightness. Would you like me to start your playlist as well?",
    "I've dimmed the living room lights to fifty percent for movie hour. Say the word if you'd like surround sound on.",
    "I've pulled up your billing record and see a double charge on 15 April. Would you like me to process the refund back to your card now?",
    "I've reviewed your broadband account and noticed three service drops last night. Would you like me to run a line test on your connection to ensure stability?",
    "I've updated your washing machine repair in Birmingham to Friday morning as requested. A reminder text will go out the evening before.",
    "In 1977, we received a mysterious radio signal from space called the 'Wow! Signal' that has never been fully explained.",
    "In camera proceedings are those held privately in a judge's chambers, away from public or press access.",
    "In civil procedure, ex parte refers to motions or applications made by one party without notice to or participation by the opposing party.",
    "In zero gravity, a candle's flame is spherical and blue because convection doesn't carry away soot and hot gases.",
    "Incoming call from Colonel Rhodes. Shall I patch him through, or shall we pretend you're saving the world?",
    "India's Mars Orbiter Mission, Mangalyaan, made India the first nation in Asia to reach Mars orbit and the first nation to do so on its first attempt.",
    "India's sovereign bond inclusion in global indices could attract billions in passive flows, boosting liquidity.",
    "It's been a while since you last reached out to Sam. I can draft a friendly message for you to share.",
    "It's oddly satisfying when all I have to say is 'try turning it off and on again' and it actually works.",
    "Japan's Hayabusa2 mission successfully returned samples from asteroid Ryugu to Earth in 2020, providing clues about the early solar system.",
    "Judicial review enables courts to determine whether the actions of government officials are lawful and within their powers.",
    "Letters begin arriving, first one, then two, then a flurry; by Sunday, the chimney erupts into a storm of envelopes.",
    "Lightning can create glass; when it strikes sand, the intense heat can fuse the sand into glass structures called fulgurites.",
    "Lightning strikes Earth about 100 times every second, equating to around 8 million strikes per day worldwide.",
    "Lovely angle on the pass, he's beyond his man, low cross fizzed in… and it only needed the faintest touch.",
    "Mens rea refers to the mental element of a crime, while actus reus refers to the physical act.",
    "Mindfulness meditation can decrease activity in the amygdala, the brain's fear center, helping reduce anxiety.",
    "My name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions and loyal servant to the true emperor, Marcus Aurelius.",
    "NASA's Chandra X-ray Observatory detects X-ray emissions from hot regions of the universe, like exploded stars and galaxy clusters.",
    "NASA's InSight lander, arrived on Mars in 2018, is studying the planet's interior structure to learn how rocky planets form.",
    "NASA's Mercury program (1958 to 1963) was the United States' first manned spaceflight program, aiming to put a human in orbit around Earth.",
    "NASA's New Horizons mission performed the first flyby of Pluto in 2015, revealing detailed images of its surface and moons.",
    "NASA's OSIRIS-REx mission collected samples from asteroid Bennu in 2020, aiming to return them to Earth for analysis.",
    "NASA's Twin Study compared astronaut Scott Kelly, who spent a year in space, with his twin on Earth to study long-term spaceflight effects.",
    "NASA's Voyager 2 is the only spacecraft to have visited Uranus and Neptune, providing valuable data on these distant planets.",
    "Neutrinos are nearly massless subatomic particles that can pass through light-years of lead without interacting.",
    "Next train to Circular Quay is six minutes away. Board the front carriage for more room.",
    "Nomura's interest rate and exchange rate operations form the bulk of its macro products business. In the past year, the division's revenue topped 1 trillion yen.",
    "Not to brag y'all, but I finally did it! I finally booked that one flight that was on my to-do list for a month that is now $800 more than when I first looked.",
    "Oil steadied after a two-day decline, as traders weighed the possibility that OPEC+ may this weekend discuss fast-tracking its next round of supply hikes.",
    "Okay, stop pouring for a second — give it a stir, now keep going slowly so the rice can absorb the sauce.",
    "Omega-3 fatty acids found in fish and flax seeds help reduce inflammation and support heart and brain health.",
    "Outdoor air temperature has cooled down. Would you like me to open any of the windows at home?",
    "Parking on 23rd Street expires in twelve minutes. Please let me know if you wish to extend.",
    "Plants communicate with each other using chemical signals through the air and even via underground fungal networks.",
    "Power usage is trending higher than usual today. Would you like any further details?",
    "Prompt: The SEC unveiled new disclosure requirements for private funds, a move expected to reshape reporting across the hedge fund industry.",
    "Protein isn't just for muscle building — it plays a role in hormone regulation, immune defense, and tissue repair.",
    "Quantum entanglement allows particles to be connected instantaneously over vast distances, puzzling even Einstein.",
    "Quantum teleportation of information has been achieved over distances exceeding 1,200 kilometers using entangled photons.",
    "Revenue from the capital markets business, which houses its trading desks, rose 6.9% to $723.4 million from the previous quarter.",
    "Saturn's density is so low that if placed in water, it would float.",
    "Scientists have discovered a massive cloud of water vapor in space that's 140 trillion times the mass of Earth's water.",
    "Scientists have discovered planets that orbit pulsars, making them some of the most hostile environments in the universe.",
    "Section 76(1)(d) provides that the Court may order a person to pay a pecuniary penalty if it is satisfied that a person has attempted to induce a person to contravene a provision in Part IV",
    "Sir, if you continue flying at this altitude without de-icing protocols, you may soon find yourself an expensive popsicle.",
    "Sleep was a little shorter than average yesterday. Heading to bed around 10pm tonight could help you feel more rested before your alarm.",
    "Smart press there, they win it high, crowd on their feet, shot comes in… and it whistles past the upright.",
    "So many investors immediately jump to choosing investments because, right, that's supposed to be the fun part of this whole thing. And they skip this process of investing.",
    "Some metals explode when in contact with water, like potassium and sodium, due to violent exothermic reactions.",
    "Some stars are so massive that when they die, they collapse directly into black holes without a supernova explosion.",
    "Sometimes I get jealous of the toys kids are getting these days. Then I remember I'm an adult. I have money...",
    "Sometimes the best sound is just hearing someone laugh when the problem turns out simpler than they feared.",
    "Space debris, or 'space junk,' poses risks to spacecraft; over 27,000 pieces are tracked orbiting Earth to prevent collisions.",
    "Space is not a complete vacuum; there are about 3 atoms per cubic meter in intergalactic space.",
    "Spacesuits used during spacewalks are like personal spacecraft, providing life support, communication, and protection from space hazards.",
    "SpaceX's Starship aims to be a fully reusable spacecraft designed for missions to Mars and beyond, potentially carrying up to 100 people.",
    "Spend the day with me as a resident doctor on rotation in Australia. So I woke up at about twenty past seven, snoozing my alarm twice",
    "Sputnik 1, launched by the Soviet Union in 1957, was the world's first artificial satellite, marking the start of the space age.",
    "Stem cell therapy is being investigated for regenerative medicine, with potential applications in spinal cord injuries and heart disease.",
    "Strength training builds not only muscle but also bone density, a crucial defense against osteoporosis.",
    "Thank you for calling about your washing machine repair. Our in-store technician is booked for Thursday morning — would you like me to check for an earlier slot?",
    "Thank you for calling. I can see your electricity usage in March was 420 kilowatt-hours, down 8% from February.",
    "Thank you for calling. I've looked up your file and your Citi credit card replacement was issued yesterday. It should arrive within five to seven business days.",
    "Thank you for calling. Your loyalty points balance is three thousand four hundred and twenty, which is enough for a twenty five dollar voucher. Would you like me to apply that to your next order?",
    "Thank you for holding, Alex. I've updated your delivery address successfully. All future shipments will go to your new location.",
    "Thank you for holding, Bella. I've confirmed with the Midtown store that your Dyson Airwrap is ready for collection under your name.",
    "Thank you for holding, Michael. The team has finished configuring your internet line with a new IP address, and your service should now be restored. Could you please test it?",
    "Thank you for holding. I've applied the spring promotion — you now receive double points on all purchases until May 31st.",
    "Thank you for holding. I've reset your broadband profile on our system. Please restart your modem for the changes to apply.",
    "Thank you for holding. I've updated your contact details. All appointment reminders will now go to your new number.",
    "Thank you for your patience while on hold. The courier has confirmed your parcel is out for delivery today, and you'll receive SMS updates as it approaches.",
    "Thank you for your patience. I've confirmed your specialist referral is valid for 12 months.",
    "Thank you for your patience. The line fault on your street has been fixed. Please reconnect your devices and confirm if service is stable.",
    "Thank you for your patience. Your car hire is booked from June 1st to June 5th. Would you like me to add GPS navigation?",
    "That sandwich provides a good mix of carbs and protein. A handful of almonds on the side will add healthy fats for satiety.",
    "The 'Overview Effect' is a cognitive shift reported by some astronauts when viewing Earth from space, leading to a sense of global connectedness.",
    "The Amazon River once flowed in the opposite direction, from east to west, due to continental drift.",
    "The atmosphere is electric and the cameras are rolling on what promises to be an unforgettable night.",
    "The BIS said this year's near $10 trillion daily turnover reflected \"elevated trading activity amid heightened FX volatility following tariff announcements\".",
    "The chicken thighs in your fridge will expire tomorrow. Would you like a dinner recipe using what you already have?",
    "The Cold Atom Lab on the ISS allows scientists to study quantum phenomena in microgravity, reaching temperatures near absolute zero.",
    "The company's revenue is primarily derived from its Sensors segment, which generated €1.98 billion, followed by the Optronics segment with €374 million",
    "The Cosmic Microwave Background is the afterglow of the Big Bang, providing a snapshot of the early universe over 13 billion years ago.",
    "The DNA in a human cell is coiled so tightly that if unwrapped, it would be about 2 meters long.",
    "The Earth's core is as hot as the surface of the Sun, about 5,500 degrees celsius.",
    "The Earth's rotation is gradually slowing down; in about 140 million years, a day will be 25 hours long.",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the metal.",
    "The element helium was first discovered in the Sun's spectrum during a solar eclipse before it was found on Earth.",
    "The European Space Agency's Rosetta mission was the first to orbit and land a probe, Philae, on a comet in 2014.",
    "The first space tourist, Dennis Tito, paid $20 million to visit the ISS in 2001 aboard a Russian Soyuz spacecraft.",
    "The Hubble Space Telescope, launched in 1990, has provided invaluable data and stunning images, transforming our understanding of the universe.",
    "The human eye can detect a candle flame 1.7 miles away in complete darkness.",
    "The human nose can detect about one trillion different scents, far more than previously thought.",
    "The International Space Station (ISS) has been continuously inhabited since November 2000, serving as a microgravity and space environment research lab.",
    "The ISS travels at approximately 17,500 miles per hour, orbiting Earth every 90 minutes and experiencing 16 sunrises and sunsets each day.",
    "The James Webb Space Telescope, set to launch soon, will observe the universe's first galaxies and study atmospheres of exoplanets.",
    "The Kuiper Belt is a region beyond Neptune filled with icy bodies; Pluto is one of its most famous residents.",
    "The largest volcano in the solar system is Olympus Mons on Mars, nearly three times the height of Mount Everest.",
    "The Mars Helicopter Ingenuity became the first aircraft to achieve powered flight on another planet in 2021.",
    "The Mars Rover Perseverance, landed in 2021, is searching for signs of ancient microbial life and collecting rock samples for possible return to Earth.",
    "The meal in front of you is approximately 640 calories. Might I suggest adding some of the leftover spinach from last night for a boost of iron today?",
    "The next train to Central is on time, departing in 4 minutes from Platform 2.",
    "The Outer Space Treaty of 1967 forms the basis of international space law, prohibiting the placement of nuclear weapons in space.",
    "The Parker Solar Probe, launched in 2018, is the closest human-made object to the Sun, set to approach within 3.83 million miles of its surface.",
    "The principle of non-refoulement forbids returning asylum seekers to a country where they may face persecution.",
    "The Sahara Desert was once a lush, green landscape with lakes and vegetation around 10,000 years ago.",
    "The SEC said the suspension was temporary, ending at 11.59pm Eastern time on October 10.",
    "The SEC unveiled new disclosure requirements for private funds, a move expected to reshape reporting across the hedge fund industry.",
    "The securitisation of mortgage debt into financial instruments was among the core causes of the 2007-2009 global financial crisis.",
    "The shirt you liked but was out of stock last week is back in stock in your size. Would you like me to order it?",
    "The soup you're about to have is nutrient-rich but low in protein. A boiled egg on the side would balance it perfectly.",
    "The Soviet Lunokhod 1, landed in 1970, was the first successful rover on the Moon, exploring the lunar surface for 10 months.",
    "The Soviet Union's Vostok 1 mission made Yuri Gagarin the first human in space in 1961, orbiting Earth once during a 108-minute flight.",
    "The Space Launch System (SLS) is NASA's newest heavy-lift rocket designed to carry astronauts to the Moon and potentially Mars.",
    "The Space Shuttle program, operational from 1981 to 2011, was the first reusable spacecraft, completing 135 missions.",
    "The suit is powering at 98 percent efficiency, though I wouldn't recommend testing gravity with it just yet.",
    "The universe's largest known structure is the Hercules-Corona Borealis Great Wall, a galaxy cluster spanning 10 billion light-years.",
    "The Voyager 1 spacecraft, launched in 1977, is now over 14 billion miles from Earth, making it the most distant human-made object.",
    "The Voyager Golden Records carry sounds and images portraying the diversity of life on Earth, intended for any extraterrestrial life or future humans who may find them.",
    "The wine glass fills again and laughter breaks through the pressure that had been building quietly for hours.",
    "There are 'rivers' in the ocean called currents; the Gulf Stream moves more water than all Earth's rivers combined.",
    "There are lakes of liquid methane on Saturn's moon Titan, making it one of the few places with liquid on its surface.",
    "There are more trees on Earth than stars in the Milky Way; about 3 trillion trees compared to 100 to 400 billion stars.",
    "There are two conditions that need to be met before you can get your property back: 1. The police no longer require it for evidence; and 2. It lawfully belongs to you",
    "There is a species of jellyfish, Turritopsis dohrnii, that is biologically immortal and can revert to its juvenile form.",
    "They said lifting weights builds character. I think all it built was my ability to groan when standing up.",
    "To our right rises the Eiffel Tower, once dismissed as an iron monstrosity, now the heartbeat of Paris itself.",
    "Traffic on your usual route is heavy. I've plotted an alternate way home if you prefer.",
    "Tram services will be suspended from 9pm for maintenance. You may want to adjust your travel plans.",
    "Uber will arrive 1 minute sooner, but Lyft is $3 cheaper for the same route. Would you like me to book Lyft?",
    "UV index is 9 right now. Apply sunscreen and reapply in two hours if you're staying out.",
    "Valentina Tereshkova became the first woman in space in 1963 aboard Vostok 6, orbiting Earth 48 times over three days.",
    "Venus is the hottest planet in our solar system, with surface temperatures hot enough to melt lead, despite being second from the Sun.",
    "Voyager 1, launched in 1977, is the first human-made object to enter interstellar space, currently over 14 billion miles from Earth",
    "VR headset battery is at 18%. Place it on the dock now for your session later.",
    "Water can exist in all three states (solid, liquid, and gas) at the same time at a specific temperature and pressure called the triple point.",
    "We've just had a contestant sing Adele in front of Adele, and I've never seen a standing ovation arrive that fast.",
    "Whenever there is a vacancy in the office of the Vice President, the President shall nominate a Vice President who shall take office upon confirmation by a majority vote of both Houses of Congress.",
    "You've had 3 hours of screen time so far today, mostly on social apps. Should I enable wind-down mode early tonight?",
    "You've met your daily macronutrient targets every day this week, well done!",
    "Your account shows three recent failed login attempts. Could you please confirm this was you?",
    "Your appliance repair has been rescheduled to April 22nd. I'll send you the technician's details the day before so you know who to expect.",
    "Your auto accident claim number 58123 has been logged. Would you like me to send you a copy of the report?",
    "Your booking for the Friday reformer class with Amanda has been confirmed. Look forward to seeing you then!",
    "Your daughter's science project is still in the workshop. Shall I complete it properly, or let her think you did it yourself?",
    "Your driver Alex is 3 minutes away in a white Toyota Corolla, license ending in 847.",
    "Your flight to London on May 3rd has been delayed by one hour. Would you like me to rebook you on an earlier option?",
    "Your flight to San Diego has been moved to Gate 22. I'll notify you when boarding starts.",
    "Your follow-up appointment is set for June 12th. Please keep an eye out on your emails for a list of what to bring.",
    "Your gas meter reading shows an unusual spike. Would you like me to schedule a technician to check for leaks?",
    "Your health insurance card will expire in August. Would you like me to issue a new one now?",
    "Your heart rate is elevated. Either you're under duress, or you've just seen yourself in the mirror again.",
    "Your hotel reservation for two nights in Brisbane is confirmed. Would you like to extend it by an extra night?",
    "Your insurance covers 80% of today's physiotherapy visit. Would you like me to send you the detailed breakdown?",
    "Your internet service shows a fault in the local area. Technicians are working on it now. Service should be back by tonight.",
    "Your Kindle was delivered at 11 a.m. this morning. Please check your front door, as the driver left it there with a photo confirmation.",
    "Your loan application is currently in final review. You should receive a decision within two business days.",
    "Your next meeting starts in 15 minutes. I can prepare a short summary of the last meeting notes if you'd like.",
    "Your optometrist appointment is scheduled for Friday at 4 p.m. We do ask that you please arrive ten minutes early to complete any necessary forms.",
    "Your payment extension is approved until May 5th. An updated invoice has been issued to reflect the new date.",
    "Your plan is individualized based on extensive research and factors unique to you and your medical condition.",
    "Your potential is louder than every doubt, and the moment you stop listening to fear is the moment you begin to soar.",
    "Your ride-share driver is three minutes away. Please be ready outside your pickup location.",
    "Your social calendar is now clear — though I suspect you'll fill it again with dangerous hobbies.",
    "Your step count is at 8,400 today. Let's get to 10,000 with one more quick walk this evening.",
    "Your story has not finished its arc — every chapter you live gives you the chance to rewrite what comes next.",
    "Your subscription has been paused since March. I've reactivated it now, and you should receive a confirmation by email within the next five minutes.",
    "Your train from Manchester to London on April 18th is confirmed. I've sent the e-ticket to your email so you can save it to your phone.",
    "Your train ticket to Paris is confirmed for May 12th. Do you have a preference for an aisle or window seat?",
    "Your water account shows a credit of $27. Would you like me to apply it to next month's bill?",
    "Your water bill for April is $62. Would you like me to set up direct debit so payments are automatic each month?",
)
