"""Fixed comparison texts for Falcon dev vs prod.

English locales (en-US / en-UK / en-IN) share ARENA_COMPARISON_TEXTS.
Hindi (hi-IN) uses HINDI_COMPARISON_TEXTS.
Bangla (bn-IN) uses BANGLA_COMPARISON_TEXTS.
Tamil (ta-IN) uses TAMIL_COMPARISON_TEXTS.
"""

from __future__ import annotations

ARENA_COMPARISON_TEXTS: tuple[str, ...] = (
    "Right, I've moved your delivery to Thursday the 14th, and, um, I'll send a text once it's out for delivery. Anything else I can sort for you?",
    'So your refund of forty-two pounds fifty has gone through, and it should land back on your card in, well, three to five working days.',
    "Okay, I've cancelled the old subscription and set up the new one starting next month. Did you want me to email a confirmation as well?",
    "Thanks for holding, I really do appreciate your patience. I've had a look and the double charge on your account, that was an error our end, so I'm putting it right now.",
    'Right, so I can see the parcel got stuck at the depot. Let me, let me just chase that for you and get it moving.',
    "I'm so sorry about the mix-up with your bill. Bear with me, um, I'll get this credited back before we hang up.",
    "Alright, I've got you in with Doctor Hayes on Monday at quarter past nine. Does that still work for you?",
    'Just ringing to remind you about your haircut tomorrow at, uh, half three with Sophie. See you then.',
    "We can do Tuesday or, I mean, Wednesday morning if that's easier. Which one suits you best?",
    "Your boiler service is booked for Friday the 9th, and the engineer'll arrive sometime between eight and twelve.",
    "Hiya, I'm calling because you're actually eligible for a cheaper tariff, and, well, I thought you'd want to know before your contract renews.",
    'No pressure at all, but if you stay with us, I can knock, um, a fiver off your monthly bill for the next year.',
    "I noticed you've not used your gym membership in a while. Would you like me to, you know, pause it rather than cancel?",
    "Before we go on, I'll just need to confirm a couple of details. Can you, can you give me the first line of your address?",
    'We spotted a login from a new device this morning. Was that, um, was that you trying to sign in?',
    "Right, that's a match, thank you. Now, just to be safe, I'll send a one-time code to your mobile ending 4471.",
    "Okay, so I'm lodging this as a first notice of loss. Can you tell me roughly what time the, the accident happened?",
    "Your claim's still being assessed, and, um, the handler should be in touch within five working days.",
    "Don't worry, I'm dispatching roadside assistance to you now. They reckon about, well, forty-five minutes to reach you.",
    "Just so I've got it right, the policy covers accidental damage but not, sorry, not wear and tear.",
    'Your current balance is one thousand, two hundred and six pounds. Would you like to hear your recent transactions too?',
    "Right, I've ordered you a new card and it should, um, it should arrive within seven working days.",
    'I can see the payment of ninety pounds went out yesterday to, let me check, to British Gas.',
    "Your loan application's been approved, and the funds'll be in your account by, well, Friday at the latest.",
    'The FTSE 100 closed up zero point four percent today, while sterling held steady against the dollar.',
    'Ten-year gilt yields edged a little higher this morning, sitting at, um, around four point one percent.',
    'Barclays reported stronger quarterly earnings, and the shares climbed roughly two percent on the news.',
    "For clarity, a force majeure clause covers events outside either party's control, such as, well, flooding or industrial action.",
    "I'm confirming your intake has been logged under reference LG-2284, and a caseworker will review it shortly.",
    'Please note that anything discussed today remains, uh, strictly confidential between yourself and the firm.',
    "Just so you're aware, this call is being recorded for training and quality purposes.",
    "You've got a fourteen-day cooling-off period, so if you change your mind, you can cancel without, um, any charge.",
    'I do need to mention the subscription renews automatically each year unless you tell us otherwise.',
    "And can I just confirm you're happy for us to, you know, keep your details on file for marketing?",
    'Okay, first thing, unplug the router at the wall and, um, give it about ten seconds before you plug it back in.',
    "Right, now look for the little reset button on the back. You'll want to, to press and hold it for five seconds.",
    'Once the light goes green, tap continue on your screen. Has it, has it turned green yet?',
    'Now scroll down to the bottom of the form and, well, just pop your postcode in that last box.',
    "I'm afraid the ten forty train to Manchester's been delayed by about twenty minutes. We're, we're really sorry for the wait.",
    "Your taxi's two minutes away in a silver Skoda, registration, um, LK19 ZTR.",
    "Right, your parcel's out for delivery today and should arrive between, let me see, one and three this afternoon.",
    "I've rebooked you onto the next flight to Edinburgh at six fifteen. Does that, does that work for you?",
    'Just a quick reminder to, um, fast from midnight before your blood test tomorrow morning.',
    'Your results have come back and everything looks fine, but the nurse will still give you a ring to go through them.',
    "Don't forget to take your, your tablets with food, and please bring your repeat prescription slip along.",
    "Before you go, would you mind rating today's call from one to five, where five is, well, very satisfied?",
    'And on a scale of nought to ten, how likely are you to recommend us to a friend?',
    'Good morning, thanks for calling Brookfield Dental. How can I, how can I help you today?',
    "Right, I'll just pop you through to the accounts team. Bear with me one moment, please.",
    "Ooh, sounds like it's chucking it down your end too. Anyway, let's get this sorted for you.",
    "Okay, so I've got your order moved to the fifteenth of March, and, um, you'll get a confirmation SMS in just a minute. Anything else I can help with?",
    'Right, your refund of one thousand two hundred rupees has been processed, and it should reflect in three to five working days.',
    "I've cancelled your monthly subscription, sorry, your yearly one, just like you asked. Would you like me to send the receipt to your email?",
    "So your account shows you've used about two GB out of the five GB plan this month. Want me to read out the remaining days too?",
    "Thank you for holding, ma'am. I've, uh, looked into the double charge, and I'm reversing the extra amount right now.",
    "I'm really sorry your parcel hasn't reached yet. Let me, let me just track it for you and see what's going on.",
    "Okay, I can see the issue with your broadband connection from here, and I'll raise a complaint with reference number BB four five two one.",
    'Thanks for calling our support line. I mean, before we begin, can you confirm the registered mobile number on the account?',
    "So I've booked your dental cleaning for Tuesday at four thirty PM with Dr Mehta. Does that time suit you?",
    'Just a quick reminder, your car service is scheduled for tomorrow morning at ten, at the Andheri workshop.',
    "Okay, um, the eleven o'clock slot is taken, but I can give you, like, eleven forty-five if that's alright?",
    'Right, so you wanted to reschedule the haircut from Saturday to, sorry, was it Sunday or Monday?',
    "Hi, I'm calling because you're, you know, eligible for a free upgrade to our hundred Mbps plan at no extra cost for three months.",
    "I noticed you've been with us for over two years now, so we'd love to offer you a little loyalty discount on your next bill.",
    'No pressure at all, but, um, would you like me to just explain how the new family plan saves you around four hundred rupees a month?',
    "We miss having you with us, honestly, and I'd, I'd really like to share an offer to win you back if you've got a minute.",
    'Alright, for security, can you, can you confirm the last four digits of your registered Aadhaar-linked number?',
    'We noticed a login from a new device in Pune this morning. Was that, uh, was that you?',
    "Okay, I've sent a one-time password to your phone. Could you read out the six digits for me once you get it?",
    "So there were three failed login attempts on your account last night. For your safety, I'm going to walk you through resetting the password.",
    "I'm sorry to hear about the accident. Let me, um, lodge a first notice of loss and get a claim number for you straight away.",
    "Your policy does cover engine damage from flooding, but, well, I'll need a copy of the FIR before we proceed.",
    "Okay, so your claim status right now is, it's under review, and our surveyor should visit within two working days.",
    "Don't worry, I'm dispatching roadside assistance to your location near the Vashi toll plaza, and they'll reach in about thirty minutes.",
    'Your current balance is, uh, eighteen thousand four hundred and fifty rupees as of today. Would you like the last five transactions as well?',
    "Right, I've blocked your old card and a new one will be couriered to your registered address within seven working days.",
    'So I can confirm your EMI of six thousand two hundred rupees was, was debited successfully this morning.',
    "Your loan application is, um, almost done, just pending one document verification, and you'll hear back by Friday.",
    'The Sensex closed up about half a percent today, while the rupee held steady around eighty-three to the dollar.',
    'Gold prices eased slightly this morning, trading near sixty-two thousand rupees for ten grams.',
    'Ten-year government bond yields ticked up to, uh, around seven point one percent in early trade.',
    'Reliance shares gained nearly two percent after the earnings update, leading the gains on the Nifty.',
    "Just so you're aware, an indemnity clause means one party agrees to cover certain losses of the other party.",
    "Okay, so I'm confirming that you've submitted your intake form, and, um, our legal team will review it within five business days.",
    'For the record, this agreement remains in force until either party gives thirty days written notice of termination.',
    'Just to let you know, this call is being recorded for quality and training purposes.',
    'So you do have a cooling-off period of, uh, fourteen days, during which you can cancel without any penalty.',
    "I should mention this plan auto-renews each year, but we'll send you a reminder before that happens, okay?",
    'Can you just confirm, for the record, that you consent to receiving promotional messages from us?',
    'Alright, first, go ahead and unplug the router, wait about ten seconds, and then, um, plug it back in.',
    'Okay, now on your screen, tap on Settings, then scroll down to, to where it says Wi-Fi, and let me know what you see.',
    'Right, press and hold the power button for, like, five seconds until the light starts blinking.',
    'So your flight to Delhi has been delayed by about forty minutes, and the new boarding time is six fifteen PM.',
    "Your cab is, uh, just two minutes away. The driver's in a white Swift, number plate ending three seven two one.",
    "Okay, I've rebooked you on the Shatabdi tomorrow morning, and your seat is, sorry, your coach is C four, seat number twelve.",
    'Hi, just a gentle reminder that your blood test report is ready, and you can collect it from the lab after two PM today.',
    'Before your appointment tomorrow, please remember not to eat or drink anything after, um, midnight, just water is fine.',
    'This is just a reminder to take your evening medication, and your follow-up with Dr Nair is on the twentieth.',
    'Before you go, on a scale of one to five, how would you rate the help you got today?',
    'Thanks for calling Sunrise Clinic. Could you tell me, are you calling about an appointment or, um, a report?',
)

HINDI_COMPARISON_TEXTS: tuple[str, ...] = (
    "ठीक है, तो आपका ऑर्डर, अम्म, कल शाम तक डिलीवर हो जाएगा। क्या मैं कोई और मदद करूँ?",
    "आपकी बुकिंग दो लोगों के लिए शुक्रवार रात आठ बजे की कन्फर्म कर दी है। कुछ और बदलना चाहेंगे?",
    "आपका रिफंड, मतलब, चार सौ निन्यानवे रुपये, तीन से पाँच दिन में वापस आ जाएगा।",
    "मैंने आपकी सब्सक्रिप्शन एक महीने के लिए, सॉरी, दो महीने के लिए पॉज़ कर दी है।",
    "होल्ड पर रुकने के लिए शुक्रिया। आपकी बिलिंग वाली दिक्कत मैंने देख ली है और अब ठीक कर देती हूँ।",
    "तो, अम्म, आपके पिछले बिल में जो दो सौ रुपये एक्स्ट्रा लगे थे, वो हम वापस कर देंगे।",
    "माफ़ कीजिए डिलीवरी लेट हुई। मैं, मैं अभी कूरियर वालों से बात करके आपको अपडेट देती हूँ।",
    "कॉल करने के लिए धन्यवाद। बताइए, आपके अकाउंट में आज क्या परेशानी आ रही है?",
    "आपकी डेंटिस्ट अपॉइंटमेंट मंगलवार सुबह साढ़े दस बजे की लगा दी है। ठीक रहेगा ना?",
    "अच्छा, तो आप उस स्लॉट को, अम्म, गुरुवार शाम को शिफ्ट करना चाहते हैं? मैं देख लेती हूँ।",
    "बस याद दिलाने के लिए कॉल किया था, कल ग्यारह बजे आपका सैलून का अपॉइंटमेंट है।",
    "डॉक्टर शर्मा अभी, अभी छुट्टी पर हैं, तो क्या मैं आपको अगले सोमवार का टाइम दे दूँ?",
    "नमस्ते, तो आपके प्लान पर अभी एक ऑफर चल रहा है। दो मिनट हैं आपके पास सुनने के लिए?",
    "देखिए, बिना ज़ोर दिए कह रही हूँ, आप सौ रुपये महीने में अनलिमिटेड डेटा पा सकते हैं।",
    "आप हमारे पुराने ग्राहक हैं, तो, अम्म, इसलिए आपके लिए एक खास विन-बैक ऑफर है।",
    "मैंने चेक किया, और आप इस अपग्रेड के लिए एलिजिबल हैं, बिल्कुल मुफ़्त में।",
    "सिक्योरिटी के लिए, क्या आप अपनी जन्मतिथि बता सकते हैं? बस कन्फर्म करना है।",
    "हमें आपके अकाउंट पर एक, अम्म, फेल्ड लॉगिन दिखा है। क्या वो आपने ही ट्राई किया था?",
    "मैंने आपके नंबर पर एक ओटीपी भेजा है, छह अंकों का। मिल गया क्या आपको?",
    "बस आख़िरी स्टेप, अपने रजिस्टर्ड ईमेल का पहला अक्षर बता दीजिए, सिर्फ़ वेरिफाई करने को।",
    "ठीक है, तो आपका क्लेम, मतलब, गाड़ी के डेंट वाला, मैंने अभी दर्ज कर लिया है।",
    "आपकी पॉलिसी में यह नुकसान कवर होता है, पर एक्सेस के तौर पर हज़ार रुपये लगेंगे।",
    "मैं रोडसाइड असिस्टेंस भेज रही हूँ, वो लगभग, अम्म, चालीस मिनट में पहुँच जाएगी।",
    "आपके क्लेम का स्टेटस अभी रिव्यू में है, क्लेम नंबर है सी एल बारह तीन चार पाँच।",
    "आपके खाते में अभी, अम्म, बारह हज़ार तीन सौ रुपये का बैलेंस है।",
    "मैंने आपके खोए हुए कार्ड को ब्लॉक कर दिया है और नया कार्ड, नया कार्ड डिस्पैच कर रही हूँ।",
    "आपका लोन एप्लिकेशन, देखिए, अभी अप्रूवल के आख़िरी चरण में है।",
    "कल आपके खाते से पाँच सौ रुपये का जो ट्रांज़ैक्शन हुआ, क्या वो आपने ही किया था?",
    "आज सेंसेक्स लगभग दो सौ अंक चढ़कर बंद हुआ, और निफ्टी भी, अम्म, थोड़ा ऊपर रहा।",
    "दस साल के बॉन्ड पर यील्ड अभी सात दशमलव एक प्रतिशत के आसपास है।",
    "सोने का भाव आज, मतलब, करीब सत्तर हज़ार रुपये प्रति दस ग्राम चल रहा है।",
    "उस कंपनी के तिमाही नतीजे उम्मीद से बेहतर रहे, मुनाफ़ा बारह प्रतिशत बढ़ा।",
    "बस साफ़ कर दूँ, इस अनुबंध में 'पक्षकार' का मतलब है दोनों हस्ताक्षर करने वाले लोग।",
    "आपकी इंटेक डिटेल्स हमें मिल गई हैं, और, अम्म, अब वो हमारी लीगल टीम को भेज दी गई हैं।",
    "यह बयान रिकॉर्ड के लिए है, आप इसे स्वेच्छा से और बिना किसी दबाव के दे रहे हैं।",
    "बस बता दूँ, यह कॉल क्वालिटी के लिए, अम्म, रिकॉर्ड की जा रही है। ठीक है आपको?",
    "आपके पास इसे रद्द करने के लिए चौदह दिन का कूलिंग ऑफ पीरियड है, बिना कोई कारण बताए।",
    "यह प्लान, मतलब, हर साल अपने आप रिन्यू हो जाएगा, जब तक आप बंद ना करें।",
    "आगे बढ़ने से पहले, क्या आप अपनी सहमति देते हैं कि हम आपका डेटा प्रोसेस करें?",
    "ठीक है, तो पहले राउटर के पीछे वाला, अम्म, छोटा बटन दस सेकंड दबाकर रखिए।",
    "अब स्क्रीन पर जहाँ 'सेटिंग्स' लिखा है ना, उस पर, उस पर टैप कीजिए।",
    "अच्छा, अब फॉर्म में अपना पिन कोड भरिए और फिर नीचे 'सबमिट' दबा दीजिए।",
    "लाइट हरी हुई? बढ़िया, इसका मतलब कनेक्शन अब, अम्म, ठीक से जुड़ गया है।",
    "माफ़ कीजिए, आपकी फ्लाइट लगभग चालीस मिनट लेट है, अब साढ़े सात बजे उड़ेगी।",
    "आपका पार्सल, अम्म, अभी रास्ते में है और कल दोपहर तक पहुँच जाएगा।",
    "आपकी टैक्सी आ रही है, ड्राइवर, सॉरी, ड्राइवर पाँच मिनट में आपके गेट पर होगा।",
    "आपकी ब्लड रिपोर्ट आ गई है, सब ठीक है। बस डॉक्टर एक बार आपसे, अम्म, बात करना चाहते हैं।",
    "बस याद दिला दूँ, कल की जाँच से पहले बारह घंटे कुछ खाना नहीं है, सिर्फ़ पानी पी सकते हैं।",
    "बस एक छोटा सवाल, एक से दस में आप आज की सर्विस को कितना देंगे?",
    "नमस्ते, आपकी कॉल का शुक्रिया। बताइए, मैं आपको किस विभाग से, अम्म, जोड़ दूँ?",
)

BANGLA_COMPARISON_TEXTS: tuple[str, ...] = (
    "আচ্ছা, আপনার যে অর্ডারটা মঙ্গলবার ডেলিভারি হওয়ার কথা ছিল, সেটা আমি বুধবারে সরিয়ে দিয়েছি। আর কোনো সাহায্য লাগবে?",
    "আপনার রিফান্ডের প্রক্রিয়া সম্পন্ন হয়েছে। টাকাটা পাঁচ থেকে সাত কর্মদিবসের মধ্যে আপনার অ্যাকাউন্টে জমা হয়ে যাবে।",
    "আপনার সাবস্ক্রিপশন এখন থেকে প্রতি মাসে দুইশো নিরানব্বই টাকায় নবায়ন হবে। এটা কি আপনার জন্য ঠিক আছে?",
    "আপনার বুকিং নিশ্চিত হয়েছে। রেফারেন্স নম্বর হলো BK7429।",
    "ধন্যবাদ ফোন করার জন্য। আপনার বিলিং-সংক্রান্ত সমস্যাটা আমি একটু দেখে নিচ্ছি।",
    "অনেকক্ষণ অপেক্ষা করার জন্য আন্তরিকভাবে দুঃখিত। আমি এখনই আপনার অভিযোগটি নথিভুক্ত করছি।",
    "দেখুন, আপনার গত মাসের বিলে যে অতিরিক্ত অর্থ কাটা হয়েছে, সেটা আমরা ফেরত দিয়ে দেব।",
    "এই অসুবিধার জন্য আমরা আন্তরিকভাবে দুঃখিত। আমি এখনই আপনার সংযোগের সমস্যাটা সমাধানের চেষ্টা করছি।",
    "তাহলে শুক্রবার সকাল এগারোটায় ডাক্তারবাবুর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট রয়েছে, ঠিক তো?",
    "আচ্ছা, আপনার স্যালনের বুকিংটা শনিবারের বদলে রবিবারে করে দেব?",
    "শুধু মনে করিয়ে দিচ্ছি, আগামীকাল বিকেল চারটায় ওয়াশিং মেশিন সারানোর টেকনিশিয়ান আপনার বাড়িতে আসবেন।",
    "বলুন তো, আপনার জন্য কোন সময়টা সুবিধাজনক হবে, সকাল না বিকেল?",
    "নমস্কার, আপনাকে একটি বিশেষ অফারের কথা জানাতে ফোন করেছি। এখন কি কথা বলার জন্য সুবিধাজনক সময়?",
    "দেখুন, আপনার বর্তমান প্ল্যানটি আপগ্রেড করলে প্রতি মাসে প্রায় দেড়শো টাকা সাশ্রয় করতে পারবেন।",
    "আপনি অনেকদিন ধরে আমাদের সঙ্গে আছেন, তাই আপনার জন্য একটি বিশেষ ছাড়ের অফার রয়েছে।",
    "কোনো তাড়া নেই। আপনি ভেবে পরে আমাদের জানাতে পারেন।",
    "নিরাপত্তার স্বার্থে, আপনার নিবন্ধিত মোবাইল নম্বরের শেষ চারটি সংখ্যা বলবেন?",
    "আপনার ফোনে একটি ওটিপি পাঠানো হয়েছে। পেয়ে থাকলে একটু পড়ে শোনাবেন?",
    "আজ সকালে আপনার অ্যাকাউন্টে লগইনের একটি চেষ্টা হয়েছিল। সেটা কি আপনিই করেছিলেন?",
    "ঠিক আছে, আপনার পরিচয় যাচাই সম্পন্ন হয়েছে। এখন বলুন, কীভাবে সাহায্য করতে পারি?",
    "আপনার গাড়ির ক্লেমটি গ্রহণ করা হয়েছে। ক্লেম নম্বর হলো CL9318।",
    "আচ্ছা, দুর্ঘটনাটি ঠিক কোথায় ঘটেছিল, একটু জানাবেন?",
    "চিন্তা করবেন না, আমি এখনই রাস্তায় সহায়তার জন্য একটি গাড়ি পাঠানোর ব্যবস্থা করছি।",
    "আপনার পলিসির আওতায় এই ক্ষতিটি অন্তর্ভুক্ত আছে কি না, আমি একটু দেখে নিচ্ছি।",
    "আপনার সেভিংস অ্যাকাউন্টে বর্তমানে বারো হাজার চারশো পঁচিশ টাকা রয়েছে।",
    "আচ্ছা, আপনার পুরোনো কার্ডটি ব্লক করে নতুন কার্ড পাঠানোর ব্যবস্থা করছি।",
    "আপনার ঋণের আবেদনটি বর্তমানে অনুমোদনের পর্যায়ে রয়েছে। দু-এক দিনের মধ্যেই আপডেট পেয়ে যাবেন।",
    "গতকাল রাত আটটায় তিন হাজার টাকার যে লেনদেনটি হয়েছে, সেটা কি আপনিই করেছিলেন?",
    "আজ বাজার কিছুটা নিম্নমুখী ছিল। সেনসেক্স প্রায় শূন্য দশমিক ছয় শতাংশ কমেছে।",
    "আজ সোনার দাম মোটামুটি স্থির রয়েছে। প্রতি দশ গ্রাম সোনার দাম প্রায় বাহাত্তর হাজার টাকার কাছাকাছি।",
    "বর্তমানে দশ বছরের সরকারি বন্ডের ইল্ড সাত দশমিক এক শতাংশের আশেপাশে রয়েছে।",
    "ওই কোম্পানির ত্রৈমাসিক ফলাফল প্রকাশিত হয়েছে। গত বছরের তুলনায় তাদের মুনাফা বারো শতাংশ বেড়েছে।",
    "সহজ করে বললে, ‘নমিনি’ হলো সেই ব্যক্তি, যাকে আপনি অর্থ গ্রহণের জন্য মনোনীত করেন।",
    "আপনার দেওয়া তথ্য আমরা সংরক্ষণ করেছি। এগুলো শুধুমাত্র এই কাজের উদ্দেশ্যেই ব্যবহার করা হবে।",
    "এই চুক্তি অনুযায়ী, যেকোনো পক্ষ ত্রিশ দিনের আগাম নোটিশ দিয়ে চুক্তি বাতিল করতে পারবেন।",
    "শুরুতেই জানিয়ে রাখছি, প্রশিক্ষণ ও মানোন্নয়নের উদ্দেশ্যে এই কলটি রেকর্ড করা হচ্ছে।",
    "আপনার কাছে চৌদ্দ দিনের সময় রয়েছে। এর মধ্যে চাইলে কোনো অতিরিক্ত খরচ ছাড়াই বাতিল করতে পারবেন।",
    "এই প্ল্যানটি এক বছর পর স্বয়ংক্রিয়ভাবে নবায়ন হবে। বিষয়টি কি আপনার জানা আছে?",
    "তাহলে আপনার সম্মতি নিয়ে আমরা এগোচ্ছি। এটা কি রেকর্ডে রাখার অনুমতি দিতে পারেন?",
    "আচ্ছা, এবার রাউটারের পেছনের লাল বোতামটি দশ সেকেন্ড চেপে ধরে রাখুন। হয়ে গেলে আমাকে জানান।",
    "এবার স্ক্রিনের নিচে যে নীল বোতামটি দেখছেন, সেটিতে ক্লিক করুন।",
    "ঠিক আছে, এবার ফোনটি সম্পূর্ণভাবে বন্ধ করে আবার চালু করুন।",
    "ফর্মের ওই ঘরে আপনার পুরো নাম লিখুন, তারপর নিচে তারিখটি লিখে দিন।",
    "একটা দুঃসংবাদ আছে। আপনার সকাল সাড়ে ছয়টার ট্রেনটি প্রায় চল্লিশ মিনিট দেরিতে চলছে।",
    "আপনার পার্সেলটি স্থানীয় হাবে পৌঁছে গেছে। আশা করছি আজ বিকেলের মধ্যেই ডেলিভারি হয়ে যাবে।",
    "আপনার ট্যাক্সি রওনা দিয়েছে। ড্রাইভার প্রায় পাঁচ মিনিটের মধ্যে পৌঁছে যাবেন।",
    "আপনার রক্ত পরীক্ষার রিপোর্ট এসে গেছে। ডাক্তারবাবু দেখে নেওয়ার পর আপনাকে জানানো হবে।",
    "শুধু মনে করিয়ে দিচ্ছি, আগামীকালের পরীক্ষার আগে রাত বারোটার পর কিছু খাবেন না।",
    "যাওয়ার আগে বলবেন, এক থেকে দশের মধ্যে আমাদের সেবাকে কত নম্বর দেবেন?",
    "উফ, আজ বেশ গরম পড়েছে, তাই না? যাই হোক, আপনার কাজটা আমি এখনই দেখে নিচ্ছি।",
)

TAMIL_COMPARISON_TEXTS: tuple[str, ...] = (
    'உங்க புக்கிங் இப்போ உறுதியாகிடுச்சு, ஞாயிறு மதியம் ஒரு மணிக்கு நாலு பேருக்கு டேபிள். வேற ஏதாவது மாத்தணுமா?',
    'சரி, உங்க ஆர்டரை, அதாவது, அந்த நீல நிற சட்டையை மீடியம் சைஸுக்கு மாத்திட்டேன். கன்ஃபர்மேஷன் மெசேஜ் உடனே வரும்.',
    'உங்க ரீஃபண்ட் ஐநூத்தி அம்பது ரூபாய், அது மூணு நாள்ள உங்க கணக்குக்கு வந்துடும்.',
    'உங்க சந்தா இந்த மாசம் இருபத்தஞ்சாம் தேதி புதுப்பிக்கப்படும், அதைப் பத்தி இப்போ சொல்லிடலாமா?',
    'எங்களை கூப்பிட்டதுக்கு நன்றி. சொல்லுங்க, உங்க பில்லில எந்த தொகை சரியில்லைனு தோணுது?',
    'ஹோல்ட்ல வெச்சதுக்கு மன்னிக்கணும். உங்க டெலிவரி இன்னிக்கு மாலைக்குள்ளார வந்துடும்னு பார்த்துட்டேன்.',
    'ஓகே, அந்த, அந்த எரர் மெசேஜ் ஏன் வருதுன்னு நான் இப்போ பார்க்கறேன், ஒரு நிமிஷம் இருங்க.',
    'உங்க புகாரை பதிவு செஞ்சிட்டேன், ரெஃபரன்ஸ் நம்பர் ஏழு நாலு இரண்டு ஒன்பது. இதை குறிச்சு வெச்சுக்கோங்க.',
    'டாக்டர் மீனாவை பார்க்க புதன்கிழமை காலை பத்து மணிக்கு நேரம் இருக்கு, அது உங்களுக்கு ஓகேவா?',
    'உங்க முடி வெட்டற அப்பாயின்ட்மென்ட்டை, என்னது, சனிக்கிழமைக்கு மாத்தணுமா? நேரம் சொல்லுங்க பார்க்கலாம்.',
    'நாளைக்கு உங்க பல் சோதனை சந்திப்பு மதியம் மூணு மணிக்கு இருக்குனு நினைவூட்டறேன்.',
    'சரி, உங்க கார் சர்வீஸ் வியாழக்கிழமை காலையில போட்டுட்டேன், ஓட்டோமேட்டிக்கா ஒரு ரிமைண்டர் வரும்.',
    'வணக்கம், உங்களுக்கு இந்த மாசம் ஒரு சிறப்பு ஆஃபர் இருக்கு, ஒரு நிமிஷம் கேட்க முடியுமா?',
    'உங்க தற்போதைய பிளானை, அதாவது, இன்னும் கொஞ்சம் டேட்டா கிடைக்கற பிளானுக்கு அப்கிரேட் பண்ண தகுதி இருக்கீங்க.',
    'நீங்க போன மாசம் கனெக்\u200cஷனை நிறுத்திட்டீங்க, திரும்ப சேர்ந்தா முதல் மூணு மாசம் பாதி விலைதான்.',
    'கட்டாயம் இல்ல, ஆனா இந்த தள்ளுபடி வெள்ளிக்கிழமைக்குள்ளார மட்டும்தான், யோசிச்சு சொல்லுங்க.',
    'பாதுகாப்புக்காக, உங்க பதிவு செஞ்ச மொபைல் நம்பருக்கு வந்த ஆறு இலக்க கோடை சொல்ல முடியுமா?',
    'உங்க கணக்கில் இன்னிக்கு காலை ஒரு புது சாதனத்துல லாகின் ஆச்சு, அது நீங்கதானா?',
    'ஓகே, உங்க, உங்க பிறந்த தேதி மட்டும் ஒரு முறை சொல்லிடுங்க, அப்புறம் தொடரலாம்.',
    'தொடர்ந்து தப்பான பாஸ்வேர்ட் முயற்சி நடந்ததால, பாதுகாப்புக்காக கணக்கை சிறிது நேரம் பூட்டிட்டோம்.',
    'உங்க கார் விபத்து பத்தி கிளைம் பதிவு செய்யலாம், முதல்ல என்ன நடந்துச்சுனு சுருக்கமா சொல்லுங்க.',
    'உங்க பாலிசி இந்த சேதத்தை கவர் பண்ணுது, ஆனா, அதாவது, கழிப்பு தொகை ஐயாயிரம் ரூபாய் இருக்கும்.',
    'உங்க கிளைம் இப்போ பரிசீலனையில இருக்கு, ஒருவேள ஒரு வாரத்துல முடிவு கிடைக்கும்.',
    'நீங்க ஹைவேல சிக்கிக்கிட்டீங்களா? சரி, உடனே ஒரு பழுது நீக்கும் வண்டியை அனுப்பறேன், எங்க இருக்கீங்க?',
    'உங்க சேமிப்பு கணக்குல இப்போ இருப்பு பதினைஞ்சாயிரத்து முன்னூறு ரூபாய் இருக்கு.',
    'உங்க தொலைஞ்ச கார்டை பிளாக் பண்ணிட்டேன், புது கார்டு, அது ஐந்து வேலை நாள்ள வீட்டுக்கு வந்துடும்.',
    'நேத்து இரண்டாயிரத்து இருநூறு ரூபாய் பணம் செலுத்தியிருக்கீங்க, அதை இப்போ உறுதி செஞ்சிக்கலாமா?',
    'உங்க கடன் விண்ணப்பம், என்னது, இப்போ இறுதி சரிபார்ப்பு நிலையில இருக்கு, இரண்டு நாள்ள தகவல் வரும்.',
    'இன்னிக்கு சென்செக்ஸ் முக்கால் சதவீதம் ஏறி எழுபதாயிரம் புள்ளியை தாண்டி மூடிச்சு.',
    'தங்கம் பத்து கிராம் இப்போ எழுபத்தி ரெண்டாயிரம் ரூபாய், நேற்றை விட கொஞ்சம் கீழ இறங்கியிருக்கு.',
    'பத்து வருஷ அரசு பத்திரத்தோட வருமானம், அதாவது, ஏழு புள்ளி ஒன்று சதவீதமா இருக்கு.',
    'அந்த நிறுவனத்தோட காலாண்டு லாபம் பன்னிரண்டு சதவீதம் கூடியிருக்கு, பங்கு விலையும் ஏறுது.',
    'இங்க சொல்லற நபர் என்பது இந்த ஒப்பந்தத்துல கையெழுத்திடற தனிநபர் அல்லது நிறுவனத்தை குறிக்கும்.',
    'உங்க இன்டேக் விவரங்களை பதிவு செஞ்சிட்டோம், இதெல்லாம் சரிங்கறதை நீங்க உறுதி பண்றீங்களா?',
    'இந்த ஒப்பந்தம் இரு தரப்பு கையெழுத்திட்ட நாள்லேருந்துதான் அமலுக்கு வரும்.',
    'இந்த அழைப்பு தர பயிற்சிக்காக பதிவு செய்யப்படுது, அது உங்களுக்கு ஓகேதானே?',
    'இந்த சந்தா, அதாவது, ஒவ்வொரு வருஷமும் தானா புதுப்பிக்கப்படும், எப்போ வேணா நீங்க ரத்து செய்யலாம்.',
    'நீங்க பதினான்கு நாள்ள மனசு மாறினா, எந்த அபராதமும் இல்லாம ரத்து செஞ்சுக்கலாம்.',
    'தொடர்வதுக்கு முன்னாடி, உங்க ஒப்புதலை ஒரு முறை வாய்வழியா சொல்லிடுங்க.',
    'முதல்ல உங்க ரவுட்டர் பின்னாடி இருக்கற பவர் பட்டனை, அதாவது, பத்து விநாடி அழுத்திப் பிடிங்க.',
    'ஓகே, இப்போ ஸ்க்ரீன்ல மேல வலது மூலையில இருக்கற செட்டிங்ஸ் ஐகானை தொடுங்க, தொடுங்க பாக்கலாம்.',
    'இப்போ ஃபார்ம்ல உங்க பெயரை டைப் பண்ணுங்க, அப்புறம், எம், நெக்ஸ்ட் பட்டனை அழுத்துங்க.',
    'கனெக்\u200cஷனை சோதிக்க, வைஃபையை ஒரு முறை ஆஃப் பண்ணி, கொஞ்சம் பொறுத்து திரும்ப ஆன் பண்ணுங்க.',
    'உங்க சென்னைக்கு போற ரயில் இன்னிக்கு, என்னது, கிட்டத்தட்ட நாற்பது நிமிஷம் தாமதமா ஓடுது.',
    'உங்க பார்சல் இப்போ உள்ளூர் கிடங்கை அடைஞ்சிருக்கு, நாளைக்கு மதியத்துக்குள்ளார டெலிவரி ஆகிடும்.',
    'உங்க டாக்ஸி வந்துட்டிருக்கு, டிரைவர் ராஜேஷ், வெள்ளை நிற கார், ஐந்து நிமிஷத்துல வந்துடுவாரு.',
    'உங்க ரத்த பரிசோதனை முடிவு வந்துடுச்சு, அதை எடுக்க நாளைக்கு கிளினிக்குக்கு வந்துடுங்க.',
    'நாளைக்கு வர முன்னாடி, அதாவது, காலையில எதுவும் சாப்பிடாம வந்துடுங்க, தண்ணி மட்டும் குடிக்கலாம்.',
    'இந்த உதவி எப்படி இருந்துச்சு, ஒன்னு தொடங்கி அஞ்சு வரைக்கும் எந்த மதிப்பெண் தருவீங்க?',
    'ஐயோ, இன்னிக்கு வெளியில ரொம்ப மழையா? இங்கயும் காலையிலேருந்து லேசா தூறிக்கிட்டே இருக்கு.',
)
