"""Fixed comparison texts for Falcon dev vs prod (shared en-US / en-UK / en-IN)."""

from __future__ import annotations

ARENA_COMPARISON_TEXTS: tuple[str, ...] = (
    "Right, I've moved your delivery to Thursday the 14th, and, um, I'll send a text once it's out for delivery. Anything else I can sort for you?",
    'So your refund of forty-two pounds fifty has gone through, and it should land back on your card in, well, three to five working days.',
    "Okay, I've cancelled the old subscription and set up the new one starting next month. Did you want me to email a confirmation as well?",
    "Thanks for holding, I really do appreciate your patience. I've had a look and the double charge on your account, that was an error our end, so I'm putting it right now.",
    'Right, so I can see the parcel got stuck at the depot. Let me, let me just chase that for you and get it moving.',
    "I'm so sorry about the mix-up with your bill. Bear with me, um, I'll get this credited back before we hang up.",
    "Alright, I've got you in with Doctor Hayes on Monday at quarter past nine. Does that still work for you?",
    'Just ringing to remind you about your haircut tomorrow at, uh, half three with Sophie. See you then.',
    "We can do Tuesday or, I mean, Wednesday morning if that's easier. Which one suits you best?",
    "Your boiler service is booked for Friday the 9th, and the engineer'll arrive sometime between eight and twelve.",
    "Hiya, I'm calling because you're actually eligible for a cheaper tariff, and, well, I thought you'd want to know before your contract renews.",
    'No pressure at all, but if you stay with us, I can knock, um, a fiver off your monthly bill for the next year.',
    "I noticed you've not used your gym membership in a while. Would you like me to, you know, pause it rather than cancel?",
    "Before we go on, I'll just need to confirm a couple of details. Can you, can you give me the first line of your address?",
    'We spotted a login from a new device this morning. Was that, um, was that you trying to sign in?',
    "Right, that's a match, thank you. Now, just to be safe, I'll send a one-time code to your mobile ending 4471.",
    "Okay, so I'm lodging this as a first notice of loss. Can you tell me roughly what time the, the accident happened?",
    "Your claim's still being assessed, and, um, the handler should be in touch within five working days.",
    "Don't worry, I'm dispatching roadside assistance to you now. They reckon about, well, forty-five minutes to reach you.",
    "Just so I've got it right, the policy covers accidental damage but not, sorry, not wear and tear.",
    'Your current balance is one thousand, two hundred and six pounds. Would you like to hear your recent transactions too?',
    "Right, I've ordered you a new card and it should, um, it should arrive within seven working days.",
    'I can see the payment of ninety pounds went out yesterday to, let me check, to British Gas.',
    "Your loan application's been approved, and the funds'll be in your account by, well, Friday at the latest.",
    'The FTSE 100 closed up zero point four percent today, while sterling held steady against the dollar.',
    'Ten-year gilt yields edged a little higher this morning, sitting at, um, around four point one percent.',
    'Barclays reported stronger quarterly earnings, and the shares climbed roughly two percent on the news.',
    "For clarity, a force majeure clause covers events outside either party's control, such as, well, flooding or industrial action.",
    "I'm confirming your intake has been logged under reference LG-2284, and a caseworker will review it shortly.",
    'Please note that anything discussed today remains, uh, strictly confidential between yourself and the firm.',
    "Just so you're aware, this call is being recorded for training and quality purposes.",
    "You've got a fourteen-day cooling-off period, so if you change your mind, you can cancel without, um, any charge.",
    'I do need to mention the subscription renews automatically each year unless you tell us otherwise.',
    "And can I just confirm you're happy for us to, you know, keep your details on file for marketing?",
    'Okay, first thing, unplug the router at the wall and, um, give it about ten seconds before you plug it back in.',
    "Right, now look for the little reset button on the back. You'll want to, to press and hold it for five seconds.",
    'Once the light goes green, tap continue on your screen. Has it, has it turned green yet?',
    'Now scroll down to the bottom of the form and, well, just pop your postcode in that last box.',
    "I'm afraid the ten forty train to Manchester's been delayed by about twenty minutes. We're, we're really sorry for the wait.",
    "Your taxi's two minutes away in a silver Skoda, registration, um, LK19 ZTR.",
    "Right, your parcel's out for delivery today and should arrive between, let me see, one and three this afternoon.",
    "I've rebooked you onto the next flight to Edinburgh at six fifteen. Does that, does that work for you?",
    'Just a quick reminder to, um, fast from midnight before your blood test tomorrow morning.',
    'Your results have come back and everything looks fine, but the nurse will still give you a ring to go through them.',
    "Don't forget to take your, your tablets with food, and please bring your repeat prescription slip along.",
    "Before you go, would you mind rating today's call from one to five, where five is, well, very satisfied?",
    'And on a scale of nought to ten, how likely are you to recommend us to a friend?',
    'Good morning, thanks for calling Brookfield Dental. How can I, how can I help you today?',
    "Right, I'll just pop you through to the accounts team. Bear with me one moment, please.",
    "Ooh, sounds like it's chucking it down your end too. Anyway, let's get this sorted for you.",
    "Okay, so I've got your order moved to the fifteenth of March, and, um, you'll get a confirmation SMS in just a minute. Anything else I can help with?",
    'Right, your refund of one thousand two hundred rupees has been processed, and it should reflect in three to five working days.',
    "I've cancelled your monthly subscription, sorry, your yearly one, just like you asked. Would you like me to send the receipt to your email?",
    "So your account shows you've used about two GB out of the five GB plan this month. Want me to read out the remaining days too?",
    "Thank you for holding, ma'am. I've, uh, looked into the double charge, and I'm reversing the extra amount right now.",
    "I'm really sorry your parcel hasn't reached yet. Let me, let me just track it for you and see what's going on.",
    "Okay, I can see the issue with your broadband connection from here, and I'll raise a complaint with reference number BB four five two one.",
    'Thanks for calling our support line. I mean, before we begin, can you confirm the registered mobile number on the account?',
    "So I've booked your dental cleaning for Tuesday at four thirty PM with Dr Mehta. Does that time suit you?",
    'Just a quick reminder, your car service is scheduled for tomorrow morning at ten, at the Andheri workshop.',
    "Okay, um, the eleven o'clock slot is taken, but I can give you, like, eleven forty-five if that's alright?",
    'Right, so you wanted to reschedule the haircut from Saturday to, sorry, was it Sunday or Monday?',
    "Hi, I'm calling because you're, you know, eligible for a free upgrade to our hundred Mbps plan at no extra cost for three months.",
    "I noticed you've been with us for over two years now, so we'd love to offer you a little loyalty discount on your next bill.",
    'No pressure at all, but, um, would you like me to just explain how the new family plan saves you around four hundred rupees a month?',
    "We miss having you with us, honestly, and I'd, I'd really like to share an offer to win you back if you've got a minute.",
    'Alright, for security, can you, can you confirm the last four digits of your registered Aadhaar-linked number?',
    'We noticed a login from a new device in Pune this morning. Was that, uh, was that you?',
    "Okay, I've sent a one-time password to your phone. Could you read out the six digits for me once you get it?",
    "So there were three failed login attempts on your account last night. For your safety, I'm going to walk you through resetting the password.",
    "I'm sorry to hear about the accident. Let me, um, lodge a first notice of loss and get a claim number for you straight away.",
    "Your policy does cover engine damage from flooding, but, well, I'll need a copy of the FIR before we proceed.",
    "Okay, so your claim status right now is, it's under review, and our surveyor should visit within two working days.",
    "Don't worry, I'm dispatching roadside assistance to your location near the Vashi toll plaza, and they'll reach in about thirty minutes.",
    'Your current balance is, uh, eighteen thousand four hundred and fifty rupees as of today. Would you like the last five transactions as well?',
    "Right, I've blocked your old card and a new one will be couriered to your registered address within seven working days.",
    'So I can confirm your EMI of six thousand two hundred rupees was, was debited successfully this morning.',
    "Your loan application is, um, almost done, just pending one document verification, and you'll hear back by Friday.",
    'The Sensex closed up about half a percent today, while the rupee held steady around eighty-three to the dollar.',
    'Gold prices eased slightly this morning, trading near sixty-two thousand rupees for ten grams.',
    'Ten-year government bond yields ticked up to, uh, around seven point one percent in early trade.',
    'Reliance shares gained nearly two percent after the earnings update, leading the gains on the Nifty.',
    "Just so you're aware, an indemnity clause means one party agrees to cover certain losses of the other party.",
    "Okay, so I'm confirming that you've submitted your intake form, and, um, our legal team will review it within five business days.",
    'For the record, this agreement remains in force until either party gives thirty days written notice of termination.',
    'Just to let you know, this call is being recorded for quality and training purposes.',
    'So you do have a cooling-off period of, uh, fourteen days, during which you can cancel without any penalty.',
    "I should mention this plan auto-renews each year, but we'll send you a reminder before that happens, okay?",
    'Can you just confirm, for the record, that you consent to receiving promotional messages from us?',
    'Alright, first, go ahead and unplug the router, wait about ten seconds, and then, um, plug it back in.',
    'Okay, now on your screen, tap on Settings, then scroll down to, to where it says Wi-Fi, and let me know what you see.',
    'Right, press and hold the power button for, like, five seconds until the light starts blinking.',
    'So your flight to Delhi has been delayed by about forty minutes, and the new boarding time is six fifteen PM.',
    "Your cab is, uh, just two minutes away. The driver's in a white Swift, number plate ending three seven two one.",
    "Okay, I've rebooked you on the Shatabdi tomorrow morning, and your seat is, sorry, your coach is C four, seat number twelve.",
    'Hi, just a gentle reminder that your blood test report is ready, and you can collect it from the lab after two PM today.',
    'Before your appointment tomorrow, please remember not to eat or drink anything after, um, midnight, just water is fine.',
    'This is just a reminder to take your evening medication, and your follow-up with Dr Nair is on the twentieth.',
    'Before you go, on a scale of one to five, how would you rate the help you got today?',
    'Thanks for calling Sunrise Clinic. Could you tell me, are you calling about an appointment or, um, a report?',
)
