#!/usr/bin/env python3
"""Build voice_battle_corpus.tsv from corpus_labels_source.tsv (label\\ttext rows)."""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "corpus_labels_source.tsv"
OUT = ROOT / "voice_battle_corpus.tsv"

# Source label -> one or more BCP-47 buckets in voice_battle_corpus.tsv
LABEL_TO_BUCKETS: dict[str, list[str]] = {
    "English (UK)": ["en-UK"],
    "English (Indian)": ["en-IN"],
    "Spanish (Spain)": ["es-ES"],
    "Hindi": ["hi-IN"],
    "French": ["fr-FR"],
    "Marathi": ["mr-IN"],
    "Tamil": ["ta-IN"],
    "Bengali (Indian)": ["bn-IN"],
    "Malayalam": ["ml-IN"],
}

# en-US reuses the UK English corpus (same lines, separate arena language).
US_FROM_BUCKET = "en-UK"


def _parse_source(text: str) -> dict[str, list[str]]:
    out: dict[str, list[str]] = defaultdict(list)
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.lower().startswith("language") and "\t" in line:
            continue
        tab = line.find("\t")
        if tab == -1:
            continue
        label = line[:tab].strip()
        sentence = line[tab + 1 :].strip()
        if label and sentence:
            out[label].append(sentence)
    return dict(out)


def main() -> None:
    if not SOURCE.is_file():
        raise SystemExit(f"Missing {SOURCE}")

    by_label = _parse_source(SOURCE.read_text(encoding="utf-8"))
    buckets: dict[str, list[str]] = defaultdict(list)

    for label, targets in LABEL_TO_BUCKETS.items():
        lines = by_label.get(label, [])
        if not lines:
            raise SystemExit(f"No lines for label: {label!r}")
        for bucket in targets:
            buckets[bucket].extend(lines)

    buckets["en-US"] = list(buckets[US_FROM_BUCKET])

    order = [
        "en-UK", "en-US", "en-IN", "es-ES", "hi-IN", "fr-FR",
        "mr-IN", "ta-IN", "bn-IN", "ml-IN",
    ]
    rows: list[str] = [
        "# Voice Arena corpus — locale<TAB>text (generated by scripts/build_voice_corpus.py)",
        "# Edit corpus_labels_source.tsv, then run: python3 scripts/build_voice_corpus.py",
        "",
    ]
    for bucket in order:
        lines = buckets.get(bucket, [])
        if not lines:
            continue
        rows.append(f"# --- {bucket} ({len(lines)} items) ---")
        for line in lines:
            rows.append(f"{bucket}\t{line}")
        rows.append("")

    OUT.write_text("\n".join(rows).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({sum(len(buckets[b]) for b in order if b in buckets)} lines)")


if __name__ == "__main__":
    main()
